[package]
name = "test-hanabi-panic"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_hanabi = "0.15.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[features]
default = ["fast-compile"]
fast-compile = ["bevy/dynamic_linking"]
